# frpc.toml
serverAddr = "{{ server_addr }}"
serverPort = {{ server_port }}

# 认证信息
auth.method = "token"
auth.token = "{{ user_token }}"

# 用户信息
user.id = "{{ user_id }}"

# 日志设置
log.to = "console"
log.level = "info"
log.maxDays = 3

# 连接设置
transport.poolCount = 1
transport.protocol = "tcp"

# 带宽限制
transport.bandwidthLimit = "{{ bandwidth_limit }}MB"

# 示例HTTP隧道配置
[[proxies]]
name = "web"
type = "http"
localPort = 80
customDomains = ["{{ domain }}"]

# 示例TCP隧道配置
[[proxies]]
name = "ssh"
type = "tcp"
localPort = 22
remotePort = {{ remote_port }}
