# frps.toml
bindPort = 7000
bindAddr = "0.0.0.0"

# 面板设置
webServer.port = 7500
webServer.addr = "0.0.0.0"

# 认证设置
auth.method = "token"
auth.token = "YOUR_DEFAULT_TOKEN"

# 日志设置
log.to = "console"
log.level = "info"
log.maxDays = 3

# 详细统计
enablePrometheus = true

# 带宽限制
transport.maxPoolCount = 100
transport.maxPortsPerClient = 0

# 自定义插件目录
pluginDir = "/var/frp/plugins"

# 连接池配置
transport.poolCount = 5

# 心跳超时
transport.heartbeatTimeout = 90
